### ISSUE TITLE
USER STORY: Site pagination

### ISSUE THREAD

**Issue by kerstin-w** [kerstin-w/Travel-Africa#3]
As a **Unregistered User** I can **view a list of posts** so that **I can select one to read.**

#20 EPIC: Blog Posts
#25 EPIC: Landing Page

## Tasks:

- [x] Create sub-page to view all posts
- [x] Add link to navbar
- [x] Order posts by date of creation
